version: '3.3'
 
services:
  tg_bot:
    build: ../tg_bot
    restart: always
    env_file:
      - ./.env
    ports:
      - "8000:8000"
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
volumes:
  postgres_data:

