version: '3.3'

services:
  db:
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  tg_bot:
    image: ryulal/tg_bot_travel:latest
    restart: always
    environment:
      TOKEN_TG: Замените:НА_ВАШ
      TOKEN_AVIASALES: Замените_НА_ВАШ
      DB_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data:
